### ISSUE TITLE
UnboundLocalError: local variable 'max_index' referenced before assignment

### ISSUE THREAD

**Issue by jwodder** [pelican-plugins/seo#8] opened 2020-08-22 23:08 UTC
* Python version: 3.8.3
* Pelican version: 4.5.0
* pelican-seo version: 1.0.0
* `pelicanconf.py`: https://gist.github.com/jwodder/35d570ca8710779af6138786b78f64da

Attempting to use this plugin on my site produces the following error:

```
-> Writing /Users/jwodder/work/GITHUB/kbits/site/build/posts/pypkg-mistakes/index.html
CRITICAL: local variable 'max_index' referenced before assignment
Traceback (most recent call last):
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/__init__.py", line 512, in main
    pelican.run()
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/__init__.py", line 121, in run
    p.generate_output(writer)
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/generators.py", line 686, in generate_output
    self.generate_pages(writer)
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/generators.py", line 595, in generate_pages
    self.generate_articles(write)
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/generators.py", line 466, in generate_articles
    write(article.save_as, self.get_template(article.template),
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/writers.py", line 269, in write_file
    _write_file(template, localcontext, self.output_path, name,
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/writers.py", line 216, in _write_file
    signals.content_written.send(path, context=localcontext)
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/plugins/seo/seo.py", line 104, in run_html_enhancer
    html_enhancements = seo_enhancer.launch_html_enhancer(
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/plugins/seo/seo_enhancer/__init__.py", line 30, in launch_html_enhancer
    "breadcrumb_schema": html_enhancer.breadcrumb_schema.create_schema(),
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/plugins/seo/seo_enhancer/html_enhancer/breadcrumb_schema_creator.py", line 100, in create_schema
    breadcrumb_items = self._create_paths()
  File "/Users/jwodder/work/GITHUB/kbits/site/.nox/publish/lib/python3.8/site-packages/pelican/plugins/seo/seo_enhancer/html_enhancer/breadcrumb_schema_creator.py", line 51, in _create_paths
    del split_path[0:max_index]
UnboundLocalError: local variable 'max_index' referenced before assignment
```

It's clear that [this condition](https://github.com/pelican-plugins/seo/blob/723bfc8b32efcbc89e0bd3ebadfa70f7cec267a6/pelican/plugins/seo/seo_enhancer/html_enhancer/breadcrumb_schema_creator.py#L47) failed to be true, and so no value was assigned to `max_index`, and yet the code used `max_index` anyway.  I'm not sure what that piece of code is meant to be doing, however, so I can't recommend a specific fix.

**Comment by MaevaBrunelles** [comment] 2020-09-06 12:51
Hi @jwodder, 

Thanks for your interest and raising an issue!
I can't reproduce the problem on my own. Following your setting file, I tried to generate an article with this input path: `src/posts/test.md` but this didn't generate a file in `build` output folder when running `pelican content`.

Can you please share me your site like you did for the setting file? Or at least, share me one Markdown page and your project tree view.

**Comment by jwodder** [comment] 2020-09-06 18:15
This is the repository for my site: <https://github.com/jwodder/kbits> (Be sure to check out the submodule for the theme as well).  If I install `pelican-seo`, change line 86 of `pelicanconf.py` to `PLUGINS = ['plugins.autopages', 'pelican.plugins.seo']`, and run `pelican -s publishconf.py`, I get the error.

**Comment by MaevaBrunelles** [comment] 2020-09-06 23:43
I think I've found the issue but I need to confirm it (not yet tested with your settings and site). 
The breadcrumb feature is based on `OUTPUT_PATH` setting, which was supposed to be one folder (`"output"`, `"build"`, ...) but not a path (currently my `OUTPUT_PATH` is equal to `'/Users/mbrunell/Documents/Dev/pelican-seo/sandbox/output'` while my setting is equal to `"output"`). So my feature failed.
I don't know if it's due to a different behavior from Pelican, maybe @justinmayer can tell me?

In any case, I'll continue to test to confirm or not this supposed root cause.

**Comment by MaevaBrunelles** [comment] 2020-09-26 19:38
Hi @jwodder,

I've just submitted a PR that fix your issue. I reproduced the issue with your site and it's now fixed on my side.

Can you test the fix by cloning the branch and tell me if everything is good in your side? If you prefer pip, you can do a `pip install git+https://github.com/pelican-plugins/seo@fix-breadcrumb-built-according-to-output-path`. 

If it works, I'll merge the PR and will see to deploy the fix.

**Comment by jwodder** [comment] 2020-09-26 20:13
@MaevaBrunelles Yes, that works.

**Closed** 2020-09-27 18:10 UTC
Labels: bug

**Comment by MaevaBrunelles** [comment] 2020-09-27 18:23
Hello @justinmayer, can you explain the process to release a new version of the plugin please?

**Comment by justinmayer** [comment] 2020-10-05 08:26
@MaevaBrunelles: Certainly. As touched on briefly in [Pelican's Contribution docs](https://docs.getpelican.com/en/latest/contribute.html#using-git-and-github), releases are issued via AutoPub + GitHub Actions when a `RELEASE.md` file is merged to the `master` branch. That will automatically increment the version number, so it's best to never manually change the version number in the `pyproject.toml` file.

As an example, such a `RELEASE.md` file could include:
```
Release type: patch

Fix breadcrumb generation from output path
```
If you intend to cover multiple fixes/features in a single release, it's best to create a list:
```
Release type: patch

* Fix breadcrumb generation from output path
* Use save_as metadata when building canonical URL
```
If you want, you could add a `RELEASE.md` file to your existing no. 10 PR. I would be happy to take a look at it and ensure it looks right before we merge it. 😄
